### ISSUE TITLE
Days parameter on sales endpoint doesn't have effect

### ISSUE THREAD

**Issue by ezolla** [botbroker/v2-api-docs#2]
# Issue

When using the sales endpoint with the "required parameters" such as days, it doesn't have any effect on the results returned by the sales endpoint from what I can tell.

## Example

Say I want the sale history of Dashe (product ID: 4) but only for the last day. I would use this endpoint, right? Below the endpoint is the result, which if you convert the epoch timestamps on them, they should be within the last day recorded right? If you test them, either the ones far down or on a further page, they are past the 1-day parameter passed to the endpoint.
```
https://api.botbroker.io/api/v2/sales?product_id=4&days=1
```
```json
{
    "pagination": {
        "next": 2,
        "page": 1,
        "per_page": 20,
        "prev": null,
        "total_count": 5291
    },
    "sort_by": "id",
    "order": "desc",
    "asks": [
        {
            "id": 81183,
            "created_at": 1605919958,
            "expiration": null,
            "key_type": "lifetime",
            "matched_at": 1605919960,
            "price": 600,
            "product_id": 4,
            "specification": null
        }
    ]
}
```

**Comment by shreyas-n** [comment]
Hey Ethan,

Thanks for making the issue. The days parameter is only required on the sales/chart endpoint, not on the regular sales endpoint. Let me know if u need any more help
